INSERT INTO tbl_items (name, img, description, shop, price, shopType) 
  VALUES("Power Treads","items/PowerTreads.jpg","A pair of tough-skinned boots that change to meet the demands of the wearer. Power Treads are assembled with Boots of Speed, Gloves of Haste, and either Belt of Strength, Robe of the Magi, or Band of Elvenskin.<br/>+8 to selected attribute<br/>Attack speed: +30<br/>Movement speed: +55","Common","1400",1);

INSERT INTO tbl_items (name, img, description, shop, price, shopType) 
  VALUES("Necronomicon","items/Necronomicon.jpg","Considered the holy grail of necromancy and demonology, a powerful malefic force is locked within its pages. The Necronomicon recipe can be purchased up to 3 times in order to increase its power. Each time it's upgraded, the strength and intelligence bonuses increase, as well as the level of the summoned units.<br/>Strength: +8/12/16<br/>Intelligence: +15/21/24","Caster","2700",0);

INSERT INTO tbl_items (name, img, description, shop, price, shopType) 
  VALUES("Dagon","items/Dagon.jpg","A lesser wand that grows in power the longer it is used, it brings magic to the fingertips of the user. Dagon is unique in that its recipe can be purchased up to 5 times in order to increase its power. Each time it's upgraded, the intelligence bonus increases, as well as the damage and casting range of its active ability, Energy Burst, and it reduces the mana cost and cooldown. <br/>Strength: +3<br/>Agility: +3<br/>Intelligence: +16/18/20/22/24<br/>Damage: +9<br/><br/>Energy burst (passive)<br/>Burst of damage to target enemy unit. Upgradable.<br/>Burst damage: 400/500/600/700/800<br/>Range: 600/650/700/750/800<br/>Cooldown: 35/30/25/20/15<br/>Mana: 180/160/140/120/100","Caster","2805 (1300)",0);

INSERT INTO tbl_items (name, img, description, shop, price, shopType) 
  VALUES("Diffusal Blade","items/DiffusalBlade.jpg","An enchanted blade that allows the user to cut straight into the enemy’s soul. Starts with 8 charges, charges are refreshed to 8 when it is upgraded.<br/>Agility: +22/26<br/>Intelligence: +6/10<br/><br/>Purge (active)<br/>Purges a target unit, removing buffs, slowing, and dealing damage if it is a summoned unit.<br/>Range: 600<br/>cooldown: 12<br/><br/>Feedback (passive)<br/>Your attacks burn 20 mana (36 mana when upgraded)  and deal the same amount in damage. Upgradable.<br /><br />Diffusal Blade is a Unique Attack Modifier, and does not stack with other Unique Attack Modifiers.","Consumables","3300 (850)",0);
